#!/bin/bash

. ./totp-ui-config

while true; do
	sleep 0.5
    while [ $(($(date +%s%30))) -gt 0 ]; do
        echo '3.33*('$(date +%s.%N)'%30)' | bc | cut -d. -f1;
        sleep 0.1;
    done | dialog --title "TOTP UI"  --gauge \
      "$(printf %$(echo "$(tput cols)*0.8/2-6" | bc)s$(oathtool $TOTP_UI_OATHTOOL_OPTIONS $TOTP_UI_SECRET))" 6 $(echo "c=$(tput cols) * 0.8; c/1" | bc);
done;
